# Skicit Bayes Classifier

We are going to train a naive Bayes classier which predicts whether a document deals with (i) apple the
IT company, or (ii) apple the fruit. To this end, you should collect a collection of documents dealing with
either topic which you should use to train and test your classier. Twenty documents in total should be
sucient in order to have good accuracy. Use 70% of your documents for training and the rest for testing.
The documents should be turned into vectors, which is needed to train the classier. In Python, we can
turn the documents into vectors in the Euclidean space as follows:
count_vect = CountVectorizer(stop_words='english')
vectors = count_vect.fit_transform(dataFiles)
X=vectors.toarray()

We then train the Naive Bayes classier in Python as follows:
clf = MultinomialNB()
clf.fit(X_train, X_train_Cl)
where we use the [multinomial Naive Bayes classier](http://scikit-learn.org/stable/modules/
generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB) . We then
predict the class of instances in the test set by using: clf:predict(X test).

 You should explain how you partitioned the data into training and test set (e.g. does the training
set contains only documents dealing with one topic?) and report the accuracy of the classier on the test
set.


## Handling the folder navigation

[How to get the directory](http://stackoverflow.com/questions/918154/relative-paths-in-python)  
[List all files in dir](http://stackoverflow.com/questions/3207219/how-to-list-all-files-of-a-directory)  
[Humanities text processing tutorial](http://nbviewer.jupyter.org/github/fbkarsdorp/python-course/blob/master/Chapter%202%20-%20First%20steps.ipynb)  


In [62]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
current_dir= os.getcwd()
task3= os.path.join(current_dir,"task3")

task3_fruit = os.path.join(task3,"fruit")
task3_computer = os.path.join(task3,"computer")

fruitTxts=[]
nerdTxts=[]
allTxts=[]

for file in os.listdir(task3_fruit):
    allTxts.append(os.path.join(task3_fruit,file))
fruitFiles=len(allTxts) 
for file in os.listdir(task3_computer):
    allTxts.append(os.path.join(task3_computer,file))
nerdFiles=len(allTxts)-fruitFiles

#dir = os.path.dirname(__file__)
#filename = os.path.join(dir, '/task3/apple 0.txt')

## Data Collection and Slicing

_**References**_

  
[Document term Matrix](https://de.dariah.eu/tatom/working_with_text.html)  
[Concate 2 numpy matrixes](http://stackoverflow.com/questions/20180210/python-how-to-combine-two-matrices-in-numpy)   


In [63]:
import numpy as np  # a conventional alia
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(input='filename', stop_words="english",decode_error='replace' )
vectors = vectorizer.fit_transform(allTxts)
vocab = vectorizer.get_feature_names()
vocab=np.array(vocab)


Y1 = np.array([1 for i in range(fruitFiles)])
Y2 = np.array([2 for i in range(nerdFiles)])
Y = np.concatenate((Y1,Y2))
X = vectors.toarray()
X1= X[:fruitFiles,:]
X2= X[fruitFiles:,:]





# X_train=np.concatenate((X1[0:6,:], X2[0:6,:]))
# Y_train=np.concatenate((Y1[0:6], Y2[0:6]))
# X_test=np.concatenate((X1[6:,:], X2[6:,:]))
# Y_test=np.concatenate((Y1[6:], Y2[6:]))



# print(np.shape(X1))
# print(np.shape(X2))
# print(np.shape(X))

   

_**Partitioning**_  

[Partiotining into training and test](http://sebastianraschka.com/Articles/2014_scikit_dataprocessing.html)    


Explain how you partitioned the data into training and test set (e.g. does the training
set contains only documents dealing with one topic?):

_As recommended in the tutorial, I used 6 files for training and 3 files for testing in both set. I trained the model with documents from both set together, although there should not be a big difference, because currently there are equal number of documents from both set. Below I have provided the logic behind partitioning of the data.
>X_train=np.concatenate((X1[0:6,:], X2[0:6,:]))  
>Y_train=np.concatenate((Y1[0:6], Y2[0:6]))  
>X_test=np.concatenate((X1[6:,:], X2[6:,:]))  
>Y_test=np.concatenate((Y1[6:], Y2[6:]))  

_**Building the model**_

[Simple MultinomialNB() example](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html)  

Report the accuracy of the classier on the test
set.

Accuracy of the test set 
Formula:

_In this case we consider class 1 as yes and class 2 as no. Accuracy = 1 on test set_
 
$$ Accuracy =  \frac{TP+TN}{TP+FP+TN+FN}$$ 

In [67]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.4, random_state=1)


print(np.shape(X_train))
print(np.shape(Y_train))

print(np.shape(X_test))
print(np.shape(Y_test))

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, Y_train)


print(clf.predict(X_test))
print(Y_test)

print(clf.score(X_test,Y_test))

(10L, 2863L)
(10L,)
(8L, 2863L)
(8L,)
[1 1 2 1 2 1 2 1]
[1 1 2 1 2 1 2 1]
1.0


## k-fold cross validation

_References_

[Cross Validation](http://scikit-learn.org/stable/modules/cross_validation.html)

We are going to evaluate the Naive Bayes classier with a k-fold cross validation using
the whole dataset collected. We consider k = 5. In Python, we can use the code below. 
Average accuracy is 1, which is good. 



In [72]:
from sklearn.model_selection import cross_val_score
data=X
label=Y
clf = MultinomialNB()
scores = cross_val_score(clf, data, label, cv=5)
print(scores)
#then you can get the mean as the k-fold cross validation value
#see more in http://scikit-learn.org/stable/modules/cross_validation.html

[ 1.  1.  1.  1.  1.]
